lst=[]
print(type(lst))
name=["John","Alice","Bob",1,3.14]
print(name)
print(name[0])
mixed_list=[1,"Hello",3.14,True]
print(mixed_list)
print(mixed_list[1])
print(mixed_list[-1])
fruits=["apple","banana","cherry"]  
print(fruits[0:2])
print(fruits[1:])
print(fruits[:2])
fruits.append("orange")
print(fruits)
fruits.insert(1,"grape")
print(fruits)
fruits[1]="kiwi"
print(fruits)
fruits.remove("banana")
print(fruits)
