lst=[]
print(type(lst))
name=["John","Alice","Bob",1,3.14]
print(name)
print(name[0])
mixed_list=[1,"Hello",3.14,True]
print(mixed_list)
print(mixed_list[1])
print(mixed_list[-1])
fruits=["apple","banana","cherry"]  
print(fruits[0:2])